name: Deno Production

## Designed toe rduce redundant doubled tests being run when doing a pr
on:
    push:
        branches: ["main"] # Run tests when merged into main and pushed to dev

permissions:
    contents: read
    id-token: write

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Setup repo
              uses: actions/checkout@v4

            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: rc

            - name: Verify formatting
              run: deno fmt --check

            - name: Deno Upgrade
              run: deno upgrade

            - name: Run linter
              run: deno lint

            - name: Run tests
              run: deno test -A

            - run: npx jsr publish
